#pragma bank 1

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ball)

const palette_color_t ball_palettes[4] = {
	RGB8(255,255,255), RGB8(172,224,139), RGB8( 52,104, 86), RGB8(  8, 24, 32)
	
};

const uint8_t ball_tiles[16] = {
	0x00,0xff,0x00,0xff,
	0x00,0xff,0x00,0xff,
	0x00,0xff,0x00,0xff,
	0x00,0xff,0x00,0xff
	
};

const metasprite_t ball_metasprite0[] = {
	METASPR_ITEM(8, 8, 0, 0), METASPR_TERM
};

const metasprite_t* const ball_metasprites[1] = {
	ball_metasprite0
};
