/*

 COLLISION_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\c_code\projects\minigames\arkanoid\res\tiles\collision_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __collision_map_h_INCLUDE
#define __collision_map_h_INCLUDE

#define collision_mapWidth 20
#define collision_mapHeight 18
#define collision_mapBank 0

extern const unsigned char collision_map[];

#endif

/* End of COLLISION_MAP.H */
